
// list item
export const LIST_ITEM_REQUEST = 'LIST_ITEM_REQUEST';
export const LIST_ITEM_SUCCESS = 'LIST_ITEM_SUCCESS';
export const LIST_ITEM_ERROR = 'LIST_ITEM_ERROR';

// add item
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const TOGGLE_FORM = 'TOGGLE_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const OPEN_FORM = 'OPEN_FORM';

// delete item
export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

// set value for updating object
export const SET_UPDATING_OBJECT_REQUEST = 'SET_UPDATING_OBJECT_REQUEST';
export const SET_UPDATING_OBJECT_SUCCESS = 'SET_UPDATING_OBJECT_SUCCESS';
export const SET_UPDATING_OBJECT_ERROR = 'SET_UPDATING_OBJECT_ERROR';

// update item
export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR';

//search 
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

//sort
export const SORT_REQUEST = 'SORT_REQUEST';
export const SORT_SUCCESS = 'SORT_SUCCESS';
export const SORT_ERROR = 'SORT_ERROR';